version: 0.0.{build}
skip_tags: true
skip_commits:
  files:
  - '**/*.md'
  - 'Res/**/*.*'
clone_script:
- sh: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    cd %APPVEYOR_BUILD_FOLDER%
    git checkout -q %APPVEYOR_REPO_COMMIT%
    git submodule update --init --recursive

environment:
  matrix:
  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2017

  - job_name: Linux build
    appveyor_build_worker_image: Ubuntu

  - job_name: macOS build
    appveyor_build_worker_image: macOS

matrix:
  fast_finish: true

# job-specific configurations
for:

  -
    matrix:
      only:
        - job_name: Windows build

    build_script:
    - cmd: cd Script
    - cmd: echo | SetupWin.bat
    - cmd: powershell -ExecutionPolicy RemoteSigned -File BuildAssimpWin-VS15.ps1 -Wait
    - cmd: powershell -ExecutionPolicy RemoteSigned -File BuildPhysXWin-VS15.ps1 -Wait
    - cmd: powershell -ExecutionPolicy RemoteSigned -File BuildGLADWin-VS15.ps1 -Wait
    - cmd: powershell -ExecutionPolicy RemoteSigned -File BuildEngineWin-VS15.ps1 -Wait

  -
    matrix:
      only:
        - job_name: Linux build

    build_script:
    - sh: cd Script
    - sh: bash SetupLinux.sh
    - sh: bash BuildAssimpLinux.sh
    - sh: bash BuildGLADLinux.sh
    - sh: bash BuildEngineLinux.sh.sh

  -
    matrix:
      only:
        - job_name: macOS build

    build_script:
    - sh: cd Script
    - sh: bash SetupMac.sh
    - sh: bash BuildAssimpMac-Xcode.sh
    - sh: bash BuildGLADMac-Xcode.sh
    - sh: bash BuildEngineMac-Clang.sh
